### ISSUE TITLE
Deprecate project

### ISSUE THREAD

**Issue by ai** [topaxi/browserslist-cli#3]
`browserslist` not has own CLI. So you can add deprecated message to README

**Comment by ai** [comment]
@topaxi what do you think about it? Right now there is a CLI tool names conflict and it confuse users https://github.com/ai/browserslist/issues/195#issuecomment-346467704

**Comment by laukstein** [comment]
The best probably would be to remove this from `npm`.

**Comment by ai** [comment]
@laukstein removing could brake current application. NPM supports `deprecate` command.

**Comment by topaxi** [comment]
I've deprecated the project on npm. If you think it is necessary to add a note to the README feel free to open a PR :)
